urls.py
from django.conf.urls import patterns, include, url
from capitalthe import settings
from django.http import HttpResponse
from django.contrib import admin
from apps.multimidia.views import PictureCreateView, PictureDeleteView
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps import Sitemap, FlatPageSitemap
from apps.materias.models import Materias
from apps.materias.feeds import UltimasNoticias, UltimasNotas

sitemaps = {
    'site': Sitemap,
    'flatpages': FlatPageSitemap,
    }

admin.autodiscover()

urlpatterns = patterns('',
     #index
     (r'^$', 'capitalthe.views.home'),
     (r'^index.php/$', 'capitalthe.views.home'),
     #(r'^admin/', include(admin.site.urls)),
     (r'^contato/$', 'capitalthe.views.contato'),
     url(r'^rss/ultimasnoticias/', UltimasNoticias()),
     url(r'^rss/ultimasnotas/', UltimasNotas()),
     # (r'^cadastrar/email/$', 'capitalteresina.contatos.views.cadastrar_email'),
     # (r'^cadastrar/sms/$', 'capitalteresina.contatos.views.cadastrar_sms'),
     #('^pages/', include('django.contrib.flatpages.urls'),

     #noticias e artigos
     (r'^noticias/$', 'apps.materias.views.noticias'),
     (r'^noticias/(?P<categoria>[\w_-]+)/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.materias.views.ver_materia'),
     (r'^noticias/imprimir/(?P<categoria>[\w_-]+)/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.materias.views.imprimir_materia'),
     (r'^noticias/(?P<categoria>[\w_-]+)/', 'apps.materias.views.ver_secao'),

     #colunas
     (r'^colunas/(?P<secao>[\w_-]+)/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.materias.views.ver_nota'),
     (r'^colunas/(?P<secao>[\w_-]+)/', 'apps.materias.views.ver_coluna'),
     (r'^colunas/$', 'apps.materias.views.colunas'),

     #albuns
     (r'^albuns/$', 'apps.multimidia.views.central_albuns'),
     (r'^albuns/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.multimidia.views.album'),
     #videos
     # (r'^videos/$', 'capitalteresina.multimidia.views.central_videos'),
     # (r'^videos/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'capitalteresina.multimidia.views.video'),
     # (r'^cultura/cinema/$', 'capitalteresina.cinema.views.cinema'),
     #jornal
     (r'^jornal/$', 'apps.jornal.views.jornal'),

     #busca
     (r'^busca/$', 'apps.materias.views.busca'),
     (r'^infograficos/$', 'apps.materias.views.infograficos'),

     #cinema
     (r'^cinema/$', 'apps.cinema.views.cinema'),
     (r'^filme/(?P<slug>[\w_-]+)', RedirectView.as_view(url='/cinema/%(slug)s/')),
     (r'^cinema/(?P<slug>[\w_-]+)', 'apps.cinema.views.filme'),

     url(r'^full128/', include(admin.site.urls)),
     url(r'^redactor/', include('redactor.urls')),
     (r'^ckeditor/', include('ckeditor.urls')),
     # (r'^adzone/', include('capitalteresina.publicidade.urls')),

     (r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nAllow: /", mimetype="text/plain")),
     (r'^sitemap\.xml$', 'capitalthe.views.sitemap'),
     (r'^sitemap-news\.xml$', 'capitalthe.views.sitemap_gnews'),

     # (r'^multimidia/foto/multiupload/$', 'apps.multimidia.views.album_id'),
     #(r'^multimidia/foto/multiupload/(?P<album_id>\d+)/$', 'apps.multimidia.views.view'),
     # (r'^multimidia/foto/multiupload/(?P<album_id>\d+)/$', 'apps.multimidia.views.album_id',),

     (r'^nup/new/(?P<album_id>\d+)/$', login_required(PictureCreateView.as_view()), {}, 'upload-new'),
     (r'^nup/delete/(?P<pk>\d+)$', login_required(PictureDeleteView.as_view()), {}, 'upload-delete'),
     ('^pages/', include('django.contrib.flatpages.urls')),
)

urlpatterns += patterns('',
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root' : settings.STATIC_ROOT}),
)

apps/materias/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.sitemaps import ping_google
from datetime import datetime
from django.contrib.contenttypes.models import ContentType
from django.db.models import signals
from django.template.defaultfilters import slugify
from apps.multimidia.models import Album, Video
from redactor.fields import RedactorField
from easy_thumbnails.fields import ThumbnailerImageField
from django.conf import settings
from image_cropping import ImageRatioField
from easy_thumbnails.files import get_thumbnailer
from tagging.fields import TagField
from tagging.utils import parse_tag_input
import lxml.html as lh
from lxml.html import builder


class Secao(models.Model):
    nome = models.CharField('Nome da Secao',max_length=35)
    url = models.SlugField('Url da Secao',max_length=35)
    descricao = models.CharField('Descricao',max_length = 150)
    dt_cadastro = models.DateTimeField(verbose_name='Data de Cadastro', auto_now_add=True)
    dt_ultAtualizacao = models.DateTimeField(verbose_name='Data Ultima Atualizacao',blank=True,default=datetime.now)
    status = models.BooleanField(verbose_name="Status", default=True)
    rodape = models.BooleanField(verbose_name="Rodape", default=False)
    secao_origem = models.ForeignKey('Secao', blank=True, null=True)

    class Meta:
        ordering = ('nome',)
        verbose_name = 'Secao'
        verbose_name_plural = 'Secoes'

    def get_absolute_url(self):
        return ('/noticias/%s/' % (self.url))

    def __unicode__(self):
        return self.nome


class Materias(models.Model):
    class Meta:
        ordering = ('-publicado_em',)
        verbose_name = u'Materia'
        verbose_name_plural = u'Materias'
        get_latest_by = 'publicado_em'

    titulo = models.CharField(max_length=90, help_text="Titulo da Noticia")
    subtitulo = models.CharField(max_length=100, help_text="Para Manchetes")
    texto = RedactorField(verbose_name="Texto")
    slug = models.SlugField(max_length=200, blank=True, unique=True)
    url = models.SlugField(max_length=200, blank=True, unique=True)

    album = models.ForeignKey(Album, blank=True, null=True,
                              help_text="Album relacionado a esta notícia. Caso esta matéria queira exibir mais de uma foto relacionada dentro da notícia.")

    # foto = models.ImageField(upload_to='uploads/materia/%Y/%m/')
    foto = ThumbnailerImageField(upload_to='materia/%Y/%m/', blank=True, help_text ="Foto destaque na materia. Dimensões 300x250")
    foto_materia = ImageRatioField('foto', '300x250')
    legenda = models.CharField(max_length=50, blank=True,
                               help_text="Se uma foto for inserida, a legenda deve ser preenchida! tamanho maximo de 30 caracteres.")
    credito = models.CharField(max_length=30, blank=True,
                               help_text="Creditos da foto.")

    # foto_destaque = models.ImageField(upload_to='uploads/materia/%Y/%m/', blank = True, null = True)
    foto_destaque = models.ImageField(upload_to='destaques/%Y/%m/', blank=True, help_text="Foto destaque dentro da materia. Dimensões 750x240")
    foto_destaque_materia = ImageRatioField('foto_destaque', '750x240')
    legenda_destaque = models.CharField(max_length=50, blank=True,
                                        help_text="Se uma foto de destaque for inserida, a legenda deve ser preenchida! tamanho maximo de 30 caracteres.")
    credito_destaque = models.CharField(max_length=30, blank=True,
                                        help_text="Creditos da foto de destaque.")

    ativarvideo = models.BooleanField(verbose_name='Utilizar Video', default=False,
                                      help_text="Habilitar o uso de um video relacionado a esta noticia")
    video = models.ForeignKey(Video, blank=True, null=True, verbose_name='Video',
                              help_text="Video relacionado a esta noticia. ")

    publicado_em = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)

    ativarcomentarios = models.BooleanField(verbose_name='Utilizar comentarios', default=True,
                                            help_text="Habilitar o uso de comentarios do Facebook")

    status = models.BooleanField(verbose_name='Noticia Ativa?', default=True,
                                 help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver esta notícia")
    #secoes
    secao = models.ForeignKey(Secao, blank=False, null=False)

    visualizacoes = models.IntegerField(default=0)
    criador = models.ForeignKey(User, blank=True, null=True, related_name='criador')
    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', blank=True)
    alterador = models.ForeignKey(User, blank=True, null=True, related_name='alterador')
    alterado_em = models.DateTimeField(verbose_name='Data da ultima alteracao', blank=True)

    fonte = models.CharField(max_length = 200, null = True, blank = True)
    autor =models.CharField(max_length = 200, null = True, blank = True)
    palavras_chaves  = TagField('palavras chaves separadas por vírgula')

    def nomeBusca(self):
        return self.titulo

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        try:
            return ('/noticias/%s/%s-%i.html' % (self.secao.url,self.slug, self.id))
        except:
            pass

    def get_print_url(self):
        try:
            return ('/noticias/imprimir/%s/%s-%i.html' % (self.secao.url,self.slug, self.id))
        except:
            pass

    def get_foto(self):
        return "/media/%s" % self.foto

    def save(self, force_insert=False, force_update=False):
        super(Materias, self).save(force_insert, force_update)
        try:
            ping_google()
        except Exception:
            pass

    def get_image_materia(self):
        return get_thumbnailer(self.foto).get_thumbnail({
            'size': (300, 250),
            'box': self.foto_materia,
            'crop': True,
            'detail': True,
            }).url

    def get_thumb_materia(self):
        return get_thumbnailer(self.foto).get_thumbnail({
            'size': (75, 75),
            'box': self.foto_materia,
            'crop': True,
            'detail': True,
            }).url

    def get_image_medium_materia(self):
        return get_thumbnailer(self.foto).get_thumbnail({
            'size': (120, 60),
            'box': self.foto_materia,
            'crop': True,
            'detail': True,
            }).url

    def get_image_full_materia(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
            'size': (750, 240),
            'box': self.foto_destaque_materia,
            'crop': True,
            'detail': True,
            }).url

    def set_tags(self, tags):
        Tag.objects.update_tags(self, tags)

    def get_tags(self, tags):
        return Tag.objects.get_for_object(self)

    def get_palavras_chaves(self):
        return parse_tag_input(self.palavras_chaves)

class Frase(models.Model):
    materia = models.ForeignKey(Materias)
    autor = models.CharField(max_length = 50)
    frase = models.CharField(max_length = 200)
    paragrafo = models.IntegerField()

class Coluna(models.Model):
    secao = models.ForeignKey(Secao)
    user = models.OneToOneField(User)
    biografia = models.TextField()
    tipo = models.CharField(max_length = 30, choices = (('Social','Social'),('Opiniao','Opiniao')))
    imagem = models.ImageField(upload_to='uploads/colunas/', help_text = "Imagem menor. Dimensões 70x70")
    imagem_thumb = ImageRatioField('foto', '70x70')
    imagem_media = models.ImageField(upload_to='uploads/colunas/', help_text = "Imagem média. Dimensões 345x100")
    imagem_media_thumb = ImageRatioField('foto', '345x100')
    imagem_header = models.ImageField(upload_to='uploads/colunas/', help_text = "Imagem no Header da Coluna. Dimensões 745x140")
    imagem_header_thumb = ImageRatioField('foto', '750x140')

    def __unicode__(self):
        return self.secao.nome

    def get_absolute_url(self):
        try:
            return ('/colunas/%s/' % (self.secao.url))
        except:
            pass

    def get_image_small(self):
        return get_thumbnailer(self.imagem).get_thumbnail({
            'size': (119, 237),
            'box': self.imagem_thumb,
            'crop': True,
            'detail': True,
            }).url

    def get_image_medium(self):
        return get_thumbnailer(self.imagem_media).get_thumbnail({
            'size': (345, 100),
            'box': self.imagem_media_thumb,
            'crop': True,
            'detail': True,
            }).url

    def get_image_header(self):
        return get_thumbnailer(self.imagem_header).get_thumbnail({
            'size': (750, 140),
            'box': self.imagem_header_thumb,
            'crop': True,
            'detail': True,
            }).url


class Nota(models.Model):
    titulo = models.CharField(max_length=100)
    nota = RedactorField('Nota',blank = True, null = True)
    primeira_foto = models.ImageField(upload_to='uploads/notas/%Y/%m/', blank = True, null = True)
    legenda_primeira_foto = models.CharField(max_length = 200, blank = True, null = True)
    segunda_foto = models.ImageField(upload_to='uploads/notas/%Y/%m/', blank = True, null = True)
    legenda_segunda_foto = models.CharField(max_length = 200, blank = True, null = True)
    secao = models.ForeignKey(Secao)
    album = models.ForeignKey(Album, blank=True, null=True,
                              help_text="Album relacionado a esta nota")
    slug = models.SlugField(max_length=200, unique=True)
    publicado_em = models.DateTimeField(default=datetime.now)
    user = models.ForeignKey(User, blank=True, null=True)
    ordem = models.IntegerField(default=99)

    def __unicode__(self):
        return self.titulo

templates/capitalteresina/noticias/imprimir.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>{{ noticia.titulo }} - Capital Teresina</title>

  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="/media/stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="/media/stylesheets/foundation.css">
  <link rel="stylesheet" href="/media/stylesheets/estilo.css">
  <link rel="stylesheet" href="/media/stylesheets/flexslider.css">


  <script src="javascripts/modernizr.foundation.js"></script>


</head>
<body>

  <header>
    <div class="row">
      <div class="four columns">
        <div id="logomarca">
          <h1><img src="/media/images/logoverde.png" /></h1>
        </div>
      </div> 

      <div class="four columns">
         <p class="p-print">versão para impressão</p>
         <div id="articleDate" class="date-print right">
         Matéria publicada: 
              <!--DATA-->{{ noticia.publicado_em|date:"d/m/Y"}}<!--/DATA-->
                -
                <!--HORA-->{{ noticia.publicado_em|date:"H:i"}}
            </div>
      </div>   
    </div>
  </header>

  <section class="conteudo">
    <div class="row">
      <div class="twelve columns text-center">
        {% if publicidades.url %}<a href="{{ publicidades.url }}">{% endif %}<embed class="ad-728x90 bt"src="/media/{{ publicidades.arquivo }}" />{% if publicidades.url %}</a>{% endif %}
      </div>
    </div>
    <div class="row">
      <div class="twelve columns">
        <section class="articleConteudo">
          <article>

            {% if noticia.foto_destaque %}
            <div class="fotodestaqueH">
                {% if noticia.credito_destaque %}<strong >Créditos: {{ noticia.credito_destaque }}</strong>{% endif %}
                <img src="{{ noticia.get_image_full_materia }}">
            </div>
            {% endif %}

            <div id="articleTitle">
                <h3>{{ noticia.titulo }}</h3>
                <p class="subtitulo">
                    {{ noticia.subtitulo }}
                </p>
            </div>

            <div id="articleBy">
                {% if noticia.autor %}<p><b>Autor: {{ noticia.autor }}</b></p>{% endif %}
            </div>

              <!-- AddThis Smart Layers BEGIN -->
              <!-- Go to http://www.addthis.com/get/smart-layers to customize -->
              <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5229ccc8349064cc"></script>
              <script type="text/javascript">
                  addthis.layers({
                      'theme' : 'transparent',
                      'share' : {
                          'position' : 'left',
                          'numPreferredServices' : 5
                      }
                  });
              </script>
              <!-- AddThis Smart Layers END -->

            {% if noticia.foto %}
            <div class="fotodestaque">
              {% if noticia.credito %}<strong >Créditos: {{ noticia.credito }}</strong>{% endif %}
              <img alt="{{ noticia.legenda }}" height="225" src="{{ noticia.get_image_materia }}" width="300">
              {% if noticia.legenda %}<strong>{{ noticia.legenda }}</strong>{% endif %}
            </div>
            {% endif %}

            <div class="articleTexto">
                {{ noticia.texto|safe }}
            </div>
              {% if noticia.album %}
              <div id="noticiaAlbum">
                  <span class="label-title"><a href="{{ noticia.album.get_absolute_url }}">Clique aqui e veja mais fotos da notícia</a></span>
              </div>
              {% endif %}
            <hr>
            {% if noticia.fonte %}
            <div class="fonte">
              <p><strong>Fonte:</strong> {{ noticia.fonte }}</p>
            </div>
            {% endif %}
          </article>
        </section>
      </div>
    </div>
  </section>

 <footer>
    <div class="row mobile-off">
        <div class="seven columns">
          <p>Rua Gabriel Ferreira, 362 - Centro Sul - Teresina/PI - (86) 3304 1004 - redacao@capitalteresina.com.br</p>
        </div>
        <div class="five columns">
          <p>&copy; copyright © 2013 — Capital Teresina.</p>
        </div>
    </div>

   
  </footer>



  <!-- Included JS Files (Compressed) -->
  <script src="javascripts/jquery.js"></script>
  <script src="javascripts/foundation.min.js"></script>

  <!-- Initialize JS Plugins -->
  <script src="javascripts/app.js"></script>
  <script type="text/javascript">
    window.print();
  </script>

</body>
</html>

templates/capitalteresina/noticias/listagem.html
{% extends "base.html" %}
{% block extra_head_content  %}
    {% include "componentes/metafb.html" %}
{% endblock %}
{% block title %}{% if secao %}{{ secao.nome|capfirst }} {% else %}Últimas Notícias {% endif %}- Capital Teresina{% endblock %}
{% block seo %}
    <meta name="description" content="{% if secao %}{{ secao.nome|capfirst }} {% else %}Últimas Notícias {% endif %}- Capital Teresina" />
    <meta name="keywords" content="capital teresina, capital teresina site, capital teresina portal" />
{% endblock %}
{% block content %}

  <section class="conteudo">
    <div class="row">
      <div class="eight columns">
        {% if flagbusca %}
        <p>Você buscou por: {{ queryb }}</p>
        {% endif %}
        {% if secao %}
        <section id="editoria-filtro">
          <div class="row">
            <div class="five columns">
              <h5>{{ secao.nome }}</h5>
            </div>
            {% if s %}
              <div class="seven columns">
                  <ul class="link-list right">
                      <li><strong>Veja também: </strong></li>
                      {% for s in secao.secao_set.all %}
                      <li><a href="{{ s.get_absolute_url }}" title="">{{ s.nome }}</a></li>
                      {% endfor %}
                      {% if secao.url == 'cultura' %}
                          <a href="/cinema">cinema</a>
                      {% endif %}
                  </ul>
              </div>
             {% endif %}
          </div>
        </section>
      {% endif %}
        {% if destaques %}
        <section id="editoria-destaque">
          <div class="row">
            {% if destaques.0 %}
            <div class="six columns mobile-two">
              <div class="ed_destaque">
                <a href="{{ destaques.0.get_absolute_url }}" title="{{ destaques.0.titulo }}">
                  <img src="/media/{{ destaques.0.foto }}" alt="{{ destaques.0.titulo }}">
                  <h5>{{ destaques.0.titulo }}</h5>
                  <p class="mobile-off">{{ destaques.0.subtitulo }}</p>
                </a>
              </div>
            </div>
            {% endif %}
            {% if destaques.1 %}
            <div class="six columns mobile-two">
                <div class="ed_destaque">
                  <a href="{{ destaques.1.get_absolute_url }}" title="{{ destaques.1.titulo }}">
                    <img src="/media/{{ destaques.1.foto }}" alt="{{ destaques.1.titulo }}">
                    <h5>{{ destaques.1.titulo }}</h5>
                    <p class="mobile-off">{{ destaques.1.titulo }}</p>
                  </a>
                </div>
            </div>
            {% endif %}
          </div>
        </section>
        {% endif %}
        <section id="editoria-listagem">
          <div class="row">
            <div class="twelve columns">
            <span class="label-title"><a href="">+ Notícias</a></span>
            <div class="row">
               {% for noticia in noticias.object_list %}
               <div class="twelve columns">
                 <div class="list-editoria">
                   <h6 class="categoria"># {{ noticia.secao.nome|lower }}</h6>
                   <h5>
                     <a href="{{ noticia.get_absolute_url }}">
                     {% if noticia.foto %}
                         <img src="{{ noticia.get_thumb_materia }}" alt="{{ noticia.titulo }}">
                     {% else %}
                         <img src="{{ MEDIA_URL }}/images/logo75x75px.jpg" alt="{{ noticia.titulo }}">
                     {% endif %}
                     <span>{{ noticia.titulo }}</span>
                         <p class="pmobile">{{ noticia.subtitulo }}</p>
                     </a>
                   </h5>
                 </div>
               </div>
                {% endfor %}

            </div>
            </div>
          </div>

          <div class="row">
            <div class="twelve columns">
              <div class="pagination-centered">
                <ul class="pagination">
                    {% if noticias.has_previous %}
                        <li class="arrow"><a href="?q={{ queryb }}&page={{ noticias.previous_page_number }}">&laquo;</a></li>
                    {% endif %}
                    {% for num in noticias.paginator.page_range %}
                        {% ifequal num noticias.number %}
                            <li class="current"><a href="">{{ num }}</a></li>
                        {% else %}
                            {% if num <= noticias.number|add:2 and num >= noticias.number|add:-2 %}
                                <li><a href="?q={{ queryb }}&page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endifequal %}
                    {% endfor %}
                    {% if noticias.has_next %}
                        <li class="arrow"><a href="?q={{ queryb }}&page={{ noticias.next_page_number }}">&raquo;</a></li>
                    {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </section>
      </div>

        {% include "componentes/sidebar.html" %}
    </div>
  </section>
{% endblock %}

templates/capitalteresina/noticias/listagem_colunas.html
{% extends "base.html" %}
{% block title %}Colunas - Capital Teresina"{% endblock %}
{% block extra_head_content  %}
    {% include "componentes/metafb.html" %}
{% endblock %}
{% block seo  %}
    <meta name="description" content="Colunas - Capital Teresina" />
    <meta name="keywords" content="capital teresina, capital teresina site, capital teresina portal, colunas" />
{% endblock %}
{% load utils %}
{% block content %}
  <section class="conteudo">
    <section id="list-colunistas">
      <div class="row">
        <div class="eight columns">
            <span class="label-title"><a href=""># Colunistas</a></span>
            <div class="row">
             {% for coluna in colunas %}
              {% if forloop.last %}
                 <div class="six columns end">
              {% else %}
                 <div class="six columns">
              {% endif %}
                <div class="item-colunista ">
                  <a href="{{ coluna.get_absolute_url }}">
                    <h5>{{ coluna.secao }}</h5>
                    <img src="{{ coluna.get_image_medium }}" alt="{{ coluna.secao }}">
                  </a>
                </div>
              </div>
             {% endfor %}
            </div>
        </div>

          {% include "componentes/sidebar.html" %}
      </div>
    </section>
  </section>
{% endblock %}