urls.py
from django.conf.urls import patterns, include, url
from capitalthe import settings
from django.http import HttpResponse
from django.contrib import admin
from apps.multimidia.views import PictureCreateView, PictureDeleteView
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps import Sitemap, FlatPageSitemap
from apps.materias.models import Materias
from apps.materias.feeds import UltimasNoticias, UltimasNotas

sitemaps = {
    'site': Sitemap,
    'flatpages': FlatPageSitemap,
    }

admin.autodiscover()

urlpatterns = patterns('',
     #index
     (r'^$', 'capitalthe.views.home'),
     (r'^index.php/$', 'capitalthe.views.home'),
     #(r'^admin/', include(admin.site.urls)),
     (r'^contato/$', 'capitalthe.views.contato'),
     url(r'^rss/ultimasnoticias/', UltimasNoticias()),
     url(r'^rss/ultimasnotas/', UltimasNotas()),
     # (r'^cadastrar/email/$', 'capitalteresina.contatos.views.cadastrar_email'),
     # (r'^cadastrar/sms/$', 'capitalteresina.contatos.views.cadastrar_sms'),
     #('^pages/', include('django.contrib.flatpages.urls'),

     #noticias e artigos
     (r'^noticias/$', 'apps.materias.views.noticias'),
     (r'^noticias/(?P<categoria>[\w_-]+)/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.materias.views.ver_materia'),
     (r'^noticias/imprimir/(?P<categoria>[\w_-]+)/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.materias.views.imprimir_materia'),
     (r'^noticias/(?P<categoria>[\w_-]+)/', 'apps.materias.views.ver_secao'),

     #colunas
     (r'^colunas/(?P<secao>[\w_-]+)/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.materias.views.ver_nota'),
     (r'^colunas/(?P<secao>[\w_-]+)/', 'apps.materias.views.ver_coluna'),
     (r'^colunas/$', 'apps.materias.views.colunas'),

     #albuns
     (r'^albuns/$', 'apps.multimidia.views.central_albuns'),
     (r'^albuns/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.multimidia.views.album'),
     #videos
     # (r'^videos/$', 'capitalteresina.multimidia.views.central_videos'),
     # (r'^videos/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'capitalteresina.multimidia.views.video'),
     # (r'^cultura/cinema/$', 'capitalteresina.cinema.views.cinema'),
     #jornal
     (r'^jornal/$', 'apps.jornal.views.jornal'),

     #busca
     (r'^busca/$', 'apps.materias.views.busca'),
     (r'^infograficos/$', 'apps.materias.views.infograficos'),

     #cinema
     (r'^cinema/$', 'apps.cinema.views.cinema'),
     (r'^filme/(?P<slug>[\w_-]+)', RedirectView.as_view(url='/cinema/%(slug)s/')),
     (r'^cinema/(?P<slug>[\w_-]+)', 'apps.cinema.views.filme'),

     url(r'^full128/', include(admin.site.urls)),
     url(r'^redactor/', include('redactor.urls')),
     (r'^ckeditor/', include('ckeditor.urls')),
     # (r'^adzone/', include('capitalteresina.publicidade.urls')),

     (r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nAllow: /", mimetype="text/plain")),
     (r'^sitemap\.xml$', 'capitalthe.views.sitemap'),
     (r'^sitemap-news\.xml$', 'capitalthe.views.sitemap_gnews'),

     # (r'^multimidia/foto/multiupload/$', 'apps.multimidia.views.album_id'),
     #(r'^multimidia/foto/multiupload/(?P<album_id>\d+)/$', 'apps.multimidia.views.view'),
     # (r'^multimidia/foto/multiupload/(?P<album_id>\d+)/$', 'apps.multimidia.views.album_id',),

     (r'^nup/new/(?P<album_id>\d+)/$', login_required(PictureCreateView.as_view()), {}, 'upload-new'),
     (r'^nup/delete/(?P<pk>\d+)$', login_required(PictureDeleteView.as_view()), {}, 'upload-delete'),
     ('^pages/', include('django.contrib.flatpages.urls')),
)

urlpatterns += patterns('',
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root' : settings.STATIC_ROOT}),
)

apps/multimidia/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime
from django.db.models import signals
from django.template.defaultfilters import slugify
from image_cropping import ImageRatioField
from easy_thumbnails.files import get_thumbnailer
from tagging.utils import parse_tag_input


class Album(models.Model):
    class Meta:
        ordering = ('-cadastrado_em',)
        verbose_name = u'Album'
        verbose_name_plural = u'Albuns'

    titulo = models.CharField(max_length=100, help_text="Titulo do album com até 100 caracteres.")
    foto_destaque = models.ImageField(upload_to='uploads/album/%Y/%m/', help_text="Foto destaque do Album. Dimensões 120x80")
    foto_medium = ImageRatioField('foto_destaque', '190x135')
    foto_big = ImageRatioField('foto_destaque', '311x200')
    foto_small = ImageRatioField('foto_destaque', '142x100')
    slug = models.SlugField(max_length=100, blank=True, unique=True)
    creditos = models.CharField(max_length = 150, blank = True, null = True)

    visualizacoes = models.IntegerField(default=0)
    publicado_em = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)
    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', default=datetime.now, blank=True)
    status = models.BooleanField(verbose_name='Ativo? ', default=True)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return ('/albuns/%s-%i.html' % (self.slug, self.id))

    def get_tag_list(self):
        return parse_tag_input(self.tags)

    def get_medium(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
            'size': (201, 150),
            'box': self.foto_medium,
            'crop': True,
            'detail': True,
            }).url

    def get_big(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
            'size': (294, 150),
            'box': self.foto_big,
            'crop': True,
            'detail': True,
            }).url

    def get_big_interna(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
            'size': (311, 200),
            'box': self.foto_big,
            'crop': True,
            'detail': True,
            }).url

    def get_small(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
            'size': (155, 150),
            'box': self.foto_small,
            'crop': True,
            'detail': True,
            }).url
    def imagemAdmin(self):
        if self.foto_destaque:
            try:
                im = get_thumbnailer(self.foto_destaque).get_thumbnail({
                    'size': (311, 200),
                    'box': self.foto_big
                })
                return '<img src="{0}" />'.format(im.url)
            except:
                return ''
        return ''
    imagemAdmin.is_safe = True
    imagemAdmin.allow_tags = True
    imagemAdmin.short_description = u'Imagem'

class Foto(models.Model):
    class Meta:
        ordering = ('-cadastrado_em',)

    foto = models.ImageField(upload_to='uploads/album/fotos/%Y/%m/')#, size=(530, 397)
    legenda = models.CharField(max_length=200, blank=True)
    foto_thumb = ImageRatioField('foto','142x100')

    album = models.ForeignKey(Album)

    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', default=datetime.now, blank=True, null = True)
    status = models.BooleanField(verbose_name='Ativo? ', default=True)

    def imagem(self):
        if self.foto:
            try:
                im = get_thumbnailer(self.foto).get_thumbnail({
                    'size': (135, 90),
                    'box': self.foto_thumb
                })
                return im.url
            except:
                return ''

        return ''
    def imagemAdmin(self):
        if self.foto:
            try:
                im = get_thumbnailer(self.foto).get_thumbnail({
                    'size': (135, 90),
                    'box': self.foto_thumb
                })
                return '<img src="{0}" />'.format(im.url)
            except:
                return ''
        return ''
    imagemAdmin.is_safe = True
    imagemAdmin.allow_tags = True
    imagemAdmin.short_description = u'Imagem'

    def __unicode__(self):
        return self.legenda

    def get_foto(self):
        return "/media/%s" % self.foto

    def get_thumb(self):
        return get_thumbnailer(self.foto).get_thumbnail({
            'size': (142, 100),
            'box': self.foto_thumb
        }).url

    def get_image(self):
        return "/media/%s" % self.foto

def album_pre_save(signal, instance, sender, **kwargs):
    """Este signal gera um slug automaticamente. Ele verifica se ja existe um
    artigo com o mesmo slug e acrescenta um numero ao final para evitar
    duplicidade"""
    if not instance.slug:
        slug = slugify(instance.titulo)
        novo_slug = slug
        contador = 0

        while Album.objects.filter(slug=novo_slug).exclude(id=instance.id).count() > 0:
            contador += 1
            novo_slug = '%s-%d'%(slug, contador)

        instance.slug = novo_slug
signals.pre_save.connect(album_pre_save, sender=Album)

class Video(models.Model):
    class Meta:
        ordering = ('-publicado_em',)

    titulo = models.CharField(max_length=100, help_text="Tamanho maximo de 100 caracteres.")
    visualizacoes = models.IntegerField(default=0)
    slug = models.SlugField(max_length=100, blank=True, unique=True)

    foto = models.ImageField(upload_to='uploads/video/%Y/%m/', null = True, blank = True)
    video = models.CharField(max_length=200, help_text="Url do Youtube")
    video_id = models.CharField(max_length=30)

    publicado_em = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now, blank=True, help_text="Data em que este video deve ser publicado.")
    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', default=datetime.now, blank=True)
    status = models.BooleanField(default=True)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return ('/videos/%s-%i.html' % (self.slug, self.id))

    def get_tag_list(self):
        return parse_tag_input(self.tags)

def video_pre_save(signal, instance, sender, **kwargs):
    """Este signal gera um slug automaticamente. Ele verifica se ja existe um
    artigo com o mesmo slug e acrescenta um numero ao final para evitar
    duplicidade"""
    novo_slug = None
    if not instance.slug:
        slug = slugify(instance.titulo)
        novo_slug = slug
        contador = 0

        while Video.objects.filter(slug=novo_slug).exclude(id=instance.id).count() > 0:
            contador += 1
            novo_slug = '%s-%d'%(slug, contador)

        instance.slug = novo_slug

signals.pre_save.connect(video_pre_save, sender=Video)

class Download(models.Model):
    class Meta:
        ordering = ('-publicado_em',)

    titulo = models.CharField(max_length=100, help_text="Tamanho maximo de 100 caracteres.")
    visualizacoes = models.IntegerField(default=0)
    slug = models.SlugField(max_length=100, blank=True, unique=True)

    arquivo = models.FileField(upload_to='uploads/downloads/%Y/%m/', help_text="Arquivo a ser baixado")

    publicado_em = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now, blank=True, help_text="Data em que este video deve ser publicado.")
    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', default=datetime.now, blank=True)
    status = models.BooleanField(default=True)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return ('/videos/%s-%i.html' % (self.slug, self.id))

    def get_tag_list(self):
        return parse_tag_input(self.tags)

def download_pre_save(signal, instance, sender, **kwargs):
    """Este signal gera um slug automaticamente. Ele verifica se ja existe um
    artigo com o mesmo slug e acrescenta um numero ao final para evitar
    duplicidade"""
    novo_slug = None
    if not instance.slug:
        slug = slugify(instance.titulo)
        novo_slug = slug
        contador = 0

        while Download.objects.filter(slug=novo_slug).exclude(id=instance.id).count() > 0:
            contador += 1
            novo_slug = '%s-%d'%(slug, contador)

        instance.slug = novo_slug

signals.pre_save.connect(download_pre_save, sender=Download)

templates/capitalteresina/album/album-view.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>View Album Capital Teresina</title>

  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="stylesheets/foundation.css">
  <link rel="stylesheet" href="stylesheets/estilo.css">
  <link rel="stylesheet" href="stylesheets/flexslider.css">

  <link rel="stylesheet" href="stylesheets/glisse.css">
  <link rel="stylesheet" href="http://capitalteresina.com.br/media/css/jquery.socialist.css">


  <script src="javascripts/modernizr.foundation.js"></script>


</head>
<body>

  <header>
    <div class="row">
      <div class="four columns">
        <div id="logomarca">
          <h1><img src="./images/logo.gif" /></h1>
        </div>
      </div>

      <div class="two columns mobile-on">
        <div id="menu-mobile">
          <div href="#" class=" button green dropdown">
            Menu
            <ul>
              <li><a href="#">inicio</a></li>
              <li><a href="#">geral</a></li>
              <li><a href="#">política</a></li>
              <li><a href="#">esportes</a></li>
              <li><a href="#">economia</a></li>
              <li><a href="#">cultura</a></li>
              <li><a href="#">colunas</a></li>
              <li><a href="#">cinema</a></li>
            </ul>
          </div>

        </div>
      </div>

      <div class="six columns">
       <div id="form-search">
         <div class="row collapse">
           <div class="ten mobile-three columns">
             <input type="text" />
           </div>
           <div class="two mobile-one columns">
             <a class="button expand postfix green">Buscar</a>
           </div>
         </div>
       </div>
      </div>
    </div>

    <div class="row mobile-off">
      <div class="twelve columns">
        <div id="menu-bar">
          <ul class="menu">
              <li><a href="#">inicio</a></li>
              <li><a href="#">geral</a></li>
              <li><a href="#">política</a></li>
              <li><a href="#">esportes</a></li>
              <li><a href="#">economia</a></li>
              <li><a href="#">cultura</a></li>
              <li><a href="#">colunas</a></li>
              <li><a href="#">cinema</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>

  <section class="conteudo">
    <section id="albuns">
      <div class="row">
        <div class="twelve columns">
            <span class="label-title"><a href=""># Albuns de fotos</a></span>
            <p class="meta-tags"><span class="secondary label">Fotos por: Gabriel Tôrres/CT</span></p>
            <div class="row">
              <div class="twelve columns">
                <div id="album-full">
                  <ul class="gallery">
                   <li><img src="http://placehold.it/240x140&text=1" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=1" title="Aenean commodo ligula eget dolor" /></li>
                    <li><img src="http://placehold.it/240x140&text=2" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=2" title="Consectetuer adipiscing elit" /></li>
                    <li><img src="http://placehold.it/240x140&text=3" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=3" title="Aenean massa" /></li>
                    <li><img src="http://placehold.it/240x140&text=4" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=4" title="Lorem ipsum dolor sit amet" /></li>
                    <li><img src="http://placehold.it/240x140&text=5" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=5" title="Dis parturient montes" /></li>
                    <li><img src="http://placehold.it/240x140&text=1" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=1" title="Aenean commodo ligula eget dolor" /></li>
                     <li><img src="http://placehold.it/240x140&text=2" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=2" title="Consectetuer adipiscing elit" /></li>
                     <li><img src="http://placehold.it/240x140&text=3" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=3" title="Aenean massa" /></li>
                     <li><img src="http://placehold.it/240x140&text=4" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=4" title="Lorem ipsum dolor sit amet" /></li>
                     <li><img src="http://placehold.it/240x140&text=5" class="myphotos" rel="group1" data-glisse-big="http://placehold.it/1024x768&text=5" title="Dis parturient montes" /></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
  </section>

  <footer>
    <div class="row mobile-off">

        <div class="four columns">
          <div id="logomarca">
            <h1><img src="./images/logo.gif" /></h1>
          </div>
        </div>
        <div class="two columns">
            <h5>geral</h5>
            <ul>
                <!-- <li><a href="/noticias/brasil" title="Brasil">Brasil</a></li> -->
                <li>Brasil</li>
                <li><a href="/noticias/teresina/" title="Teresina">Teresina</a></li>
                <li><a href="/noticias/ciencia-e-saude/" title="Ciência e Saúde">Ciência e Saúde</a></li>
                <li><a href="/noticias/educacao" title="Educação">Educação</a></li>
            </ul>
        </div>
        <div class="two columns">
            <h5>política</h5>
            <ul>
                <li><a href="/noticias/piaui" title="Piauí">Piauí</a></li>
                <li><a href="/noticias/nacional" title="Nacional">Nacional</a></li>
                <li>Mundo</li>
            </ul>
        </div>
        <div class="two columns">
            <h5>economia</h5>
            <ul>
                <li>Finanças Pessoais</li>
                <li>Agronegócio</li>
                <li>Empreendedorismo</li>
                <li><a href="/noticias/concursos-e-empregos/" title="Concursos e Empregos">Concursos e Empregos</a></li>
            </ul>
        </div>
        <div class="two columns">
            <h5>cultura</h5>
            <ul>
                <li><a href="/noticias/agenda-de-eventos/" title="Agenda de Eventos">Agenda de Eventos</a></li>
                <li><a href="/cinema/" title="Cinema">Cinema</a></li>
                <li>Celebridades</li>
                <li>Novelas</li>
            </ul>
        </div>
    </div>

    <div class="row">
      <hr>
      <div class="six columns">
        <p>Rua Gabriel Ferreira, 362 - Centro Sul - Teresina/PI - (86) 3304 1004 - redacao@capitalteresina.com.br</p>
      </div>

      <div class="six columns">
        <ul class="link-list right">
          <li><a href="/privacidade" title="">política de privacidade</a></li>
          <li><a href="/contato/" title="Contato">contato</a></li>
          <li><a href="/anuncie/" title="Anuncie">anuncie conosco</a></li>
        </ul>
      </div>

    </div>
      <div class="row">
        <hr>
        <div class="six columns">
          <p>&copy; copyright © 2013 — Capital Teresina.</p>
        </div>
      </div>
    </div>
  </footer>



  <!-- Included JS Files (Compressed) -->
  <script src="javascripts/jquery.js"></script>
  <script src="javascripts/foundation.min.js"></script>

  <!-- Initialize JS Plugins -->
  <script src="javascripts/app.js"></script>
  <script type="text/javascript" src="javascripts/flexslider.js"></script>
  <script type="text/javascript" src="javascripts/glisse.js"></script>
  <script type="text/javascript" src=" http://capitalteresina.com.br/media/js/jquery.socialist.js"></script>

  <script type="text/javascript">
      $(document).ready(function() {
          $('#main-slider').flexslider({animation: 'fade', controlsContainer: '.flex-container'});
      });
  </script>

  <script>
    $(function () {
        $('.myphotos').glisse({speed: 500, changeSpeed: 550, effect:'bounce', fullscreen: false});
    });
  </script>




</body>
</html>

templates/capitalteresina/album/album.html
{% extends "base.html" %}
{% block extra_head_content  %}
    <meta property="og:site_name" content="Capital Teresina" />
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="pt_BR" />
    <meta property="fb:app_id" content="393767570714772" />
    <meta property="og:url" content="http://www.capitalteresina.com.br/{{ request.get_full_path }}" />
    <meta property="og:title" content="{{ album.titulo }} - Capital Teresina" />
    <meta property="og:image" content="http://www.capitalteresina.com.br/media/{{ album.foto_destaque }}" />
    <meta property="og:description" content="{{ album.titulo }}" />
    <meta property="article:published_time" content="{{ album.publicado_em|date:'Y-m-d'}}" />
    <meta property="article:modified_time" content="{{ album.publicado_em|date:'Y-m-d'}}" />

{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/foundation.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/estilo.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/flexslider.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/glisse.css">
{% endblock %}
{% block seo  %}
    <meta name="description" content="{{ album.titulo }} - Capital Teresina" />
    <meta name="keywords" content="capital teresina, capital teresina site, capital teresina portal" />
{% endblock %}
{% block title %}{{ album.titulo }} - Capital Teresina{% endblock %}
{% block content %}
  <section class="conteudo">
    <section id="albuns">
      <div class="row">
        <div class="twelve columns">
            <span class="label-title"><a href=""># {{ album.titulo }}</a></span>
            {% if album.creditos %}<p class="meta-tags"><span class="secondary label">Fotos por: {{ album.creditos }}</span></p>{% endif %}
            <div class="row">
              <div class="twelve columns">
                <div id="album-full">
                  <ul class="gallery">
                   {% for foto in album.foto_set.all %}
                      <li><img src="{{ foto.get_thumb }}" class="myphotos" rel="group1" data-glisse-big="{{ foto.get_foto }}" title="{{ foto.legenda }}" /></li>
                   {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
  </section>

{% endblock %}

{% block extrajs %}
  <!-- Included JS Files (Compressed) -->
  <script src="{{ MEDIA_URL }}javascripts/jquery.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/foundation.min.js"></script>

  <!-- Initialize JS Plugins -->
  <script src="{{ MEDIA_URL }}javascripts/app.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}javascripts/flexslider.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}javascripts/glisse.js"></script>
<!--  <script type="text/javascript" src=" http://capitalteresina.com.br/media/js/jquery.socialist.js"></script>-->

  <script type="text/javascript">
      $(document).ready(function() {
          $('#main-slider').flexslider({animation: 'fade', controlsContainer: '.flex-container'});
      });
  </script>

  <script>
    $(function () {
        $('.myphotos').glisse({speed: 500, changeSpeed: 550, effect:'bounce', fullscreen: false});
    });
  </script>
{% endblock %}

templates/capitalteresina/album/central.html
{% extends "base.html" %}
{% block title %}Álbuns - Capital Teresina{% endblock %}
{% block seo  %}
    <meta name="description" content="Álbuns - Capital Teresina" />
    <meta name="keywords" content="capital teresina, capital teresina site, capital teresina portal" />
{% endblock %}
{% block content %}

  <section class="conteudo">
    <section id="albuns">
      <div class="row">
        <div class="eight columns">
            <span class="label-title"><a href=""># Albuns de fotos</a></span>
            <div class="row">
              {% for album in albuns %}
              {% if forloop.last %}
                <div class="six columns mobile-two end">
              {% else %}
                <div class="six columns mobile-two">
              {% endif %}
                <div class="album-big">
                  <a href="{{ album.get_absolute_url }}">
                     <img src="{{ album.get_big_interna }}">
                     <span class="caption">{{ album.titulo }}</span>
                  </a>
                </div>
              </div>
                {% endfor %}
            </div>

            <div class="row">
              <div class="twelve columns">
                <div class="pagination-centered">
                  <ul class="pagination">
                      {% if albuns.has_previous %}
                          <li class="arrow"><a href="?q={{ queryb }}&page={{ albuns.previous_page_number }}">&laquo;</a></li>
                      {% endif %}
                      {% for num in albuns.paginator.page_range %}
                          {% ifequal num albuns.number %}
                              <li class="current"><a href="">{{ num }}</a></li>
                          {% else %}
                              {% if num <= albuns.number|add:2 and num >= albuns.number|add:-2 %}
                                  <li><a href="?q={{ queryb }}&page={{ num }}">{{ num }}</a></li>
                              {% endif %}
                          {% endifequal %}
                      {% endfor %}
                      {% if albuns.has_next %}
                          <li class="arrow"><a href="?q={{ queryb }}&page={{ albuns.next_page_number }}">&raquo;</a></li>
                      {% endif %}
                  </ul>
                </div>
              </div>
            </div>
            <hr>
        </div>

          {% include "componentes/sidebar.html" %}
      </div>
    </section>

  </section>
{% endblock %}